#!/bin/bash

# ============================================================
# LoTS-Net semi-supervised training script
# ============================================================

export CUDA_VISIBLE_DEVICES=0,1
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
NUM_GPUS=2
MASTER_PORT=$(python3 -c "
import socket
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind(('', 0))
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    print(s.getsockname()[1])
")
echo "[INFO] Using master port: $MASTER_PORT"

SEED=42
NUM_WORKERS=1

# ---- Data ----
# DATA_ROOT="data/GPCC_Resized_512_640_to_256_256_overlap_0_0"          # Replace with your data path
DATA_ROOT="data/MDC_Resized_256_320_to_256_256_overlap_0_0"          # Replace with your data path
LABEL_RATIO=0.2
VAL_RATIO=0.1
TEST_RATIO=0.1

# ---- Dataset split mode ----
# ""                           -> random split (default), four-way random partition
# "data/.../split_semi.csv"    -> CSV preset split (recommended), generated by dataview.ipynb
#                                CSV must contain 'case_id' and 'split'
#                                (train_labeled/train_unlabeled/val/test) columns
#                                When set, LABEL_RATIO/VAL_RATIO/TEST_RATIO are ignored
# SPLIT_CSV=""
SPLIT_CSV="data/MDC_Resized_256_320_to_256_256_overlap_0_0/split_semi.csv"

# ---- Training hyperparameters (aligned with supervised) ----
BATCH_SIZE=2
EPOCHS=150
LR=0.0004
NUM_CLASSES=2

# ---- LR schedule (semi-specific: warmup -> plateau -> cosine) ----
WARMUP_RATIO=0.4
PLATEAU_RATIO=0.1
RAMPUP_RATIO=0.333

# ---- Semi-supervised loss weights (semi-specific) ----
PL_CONF_THRESH=0.70
LAMBDA_AUX=0.4              # aligned with supervised LAMBDA_AUX_SUP
GAMMA=0.5
LAMBDA_MAX=0.4

# ---- Early stopping ----
# Monitor Val Dice: stop after consecutive epochs without improvement; 0 = disabled
EARLY_STOP_PATIENCE=0

# ---- Window-best model checkpoint ----
BEST_WINDOW_START=50
BEST_WINDOW_END=100

# ---- Model hyperparameters (aligned with supervised) ----
# IN_CHANS=40
IN_CHANS=60
C_SPE=144
C_ATTN=144
ROUTER_TOP_K=15
STEM_CH=128
QUEUE_LEN=300
QUEUE_DEVICE="cuda"         # "cpu" or "cuda" (cuda reduces CPU->GPU transfer latency)

# ---- Queue retrieval mode ----
# "top1"    : paper Eq.1, global pool + argmax, very low VRAM (recommended)
# "chunked" : online-softmax chunked dense attention, numerically equivalent, bounded VRAM
RETRIEVAL_MODE="chunked"
QUEUE_CHUNK_SIZE=32         # chunked mode only: queue entries per chunk

# ---- Router temperature ----
# Top-K logits from scoring_mlp are divided by this temperature before softmax
# < 1.0 -> sharper weights (closer to hard selection, more focused gradients)
# > 1.0 -> softer weights (more uniform aggregation, better early exploration)
# 1.0   -> no scaling (default)
ROUTER_TEMPERATURE=1.0

# ---- SMD EMA bases ----
# "--smd_ema_bases"  -> enable (strongly recommended): persistent NMF bases + EMA update
# ""                -> disable: random NMF init every forward (original behavior, not recommended)
SMD_EMA_BASES="--smd_ema_bases"

# ---- DDP options ----
# "--find_unused_parameters" -> enable (for ablation runs with unused parameters)
# ""                         -> disable (lower comm overhead when all params are used)
FIND_UNUSED_PARAMS=""

# ---- Dice loss class weights ----
# ""                                  -> omit flag, equal bg/fg weights (default)
# "--dice_class_weights 0.0 1.0"      -> foreground-only Dice (ignore background)
# "--dice_class_weights 0.3 1.0"      -> foreground weight ~3.3x background
# "--dice_class_weights 0.5 1.0"      -> foreground weight 2x background (recommended start)
DICE_CLASS_WEIGHTS="--dice_class_weights 0.5 1.0"

# ---- CE loss class weights ----
# ""                                      -> omit flag, equal average (default)
# "--ce_class_weights 1.0 1.8"            -> fg weight 1.0, bg weight 1.8 (recommended)
CE_CLASS_WEIGHTS=""

# ---- CE/Dice global coefficients ----
# loss = ce_weight*CE + dice_weight*Dice
CE_WEIGHT=1.0
DICE_WEIGHT=1.0

# ---- Semi-supervised text encoding (semi-specific; default matches supervised dataset) ----
TEXT_ENCODER="default"
TEXT_MODE="default"
ROUTER_SCORE_NOISE_STD=0.0  # not exposed in supervised script; default 0.0

# ---- Logging ----
PROGRESS="log"              # tqdm / log / none
LOG_INTERVAL=20
NUM_TOP_K_BATCHES=20
TIMESTAMP=$(date "+%Y%m%d_%H%M%S")
EXP_NAME="Semi_LoTSNet_${TIMESTAMP}"
SAVE_DIR="./records/${EXP_NAME}"
mkdir -p "$SAVE_DIR"

echo "========================================================"
echo "Starting Semi-Supervised Training on $NUM_GPUS GPUs..."
echo "Experiment:      $EXP_NAME"
echo "Queue device:    $QUEUE_DEVICE"
echo "Retrieval mode:  $RETRIEVAL_MODE"
echo "Find unused:     ${FIND_UNUSED_PARAMS:-false}"
echo "Progress mode:   $PROGRESS"
echo "========================================================"

torchrun \
    --nproc_per_node=$NUM_GPUS \
    --master_port=$MASTER_PORT \
    train_semi.py \
    --seed $SEED \
    --num_workers $NUM_WORKERS \
    --save_dir "$SAVE_DIR" \
    --exp_name "$EXP_NAME" \
    --data_root "$DATA_ROOT" \
    --label_ratio $LABEL_RATIO \
    --val_ratio $VAL_RATIO \
    --test_ratio $TEST_RATIO \
    ${SPLIT_CSV:+--split_csv "$SPLIT_CSV"} \
    --use_l_pl \
    --use_l_con \
    --img_size 256 256 \
    --epochs $EPOCHS \
    --batch_size $BATCH_SIZE \
    --lr $LR \
    --num_classes $NUM_CLASSES \
    --warmup_ratio $WARMUP_RATIO \
    --early_stop_patience $EARLY_STOP_PATIENCE \
    --best_window_start $BEST_WINDOW_START \
    --best_window_end $BEST_WINDOW_END \
    --in_chans $IN_CHANS \
    --c_spe $C_SPE \
    --c_attn $C_ATTN \
    --router_top_k $ROUTER_TOP_K \
    --stem_ch $STEM_CH \
    --queue_len $QUEUE_LEN \
    --queue_device $QUEUE_DEVICE \
    --retrieval_mode $RETRIEVAL_MODE \
    --queue_chunk_size $QUEUE_CHUNK_SIZE \
    --router_temperature $ROUTER_TEMPERATURE \
    $SMD_EMA_BASES \
    $FIND_UNUSED_PARAMS \
    $DICE_CLASS_WEIGHTS \
    $CE_CLASS_WEIGHTS \
    --ce_weight $CE_WEIGHT \
    --dice_weight $DICE_WEIGHT \
    --lambda_aux $LAMBDA_AUX \
    --pl_conf_thresh $PL_CONF_THRESH \
    --plateau_ratio $PLATEAU_RATIO \
    --rampup_ratio $RAMPUP_RATIO \
    --lambda_max $LAMBDA_MAX \
    --gamma $GAMMA \
    --router_score_noise_std $ROUTER_SCORE_NOISE_STD \
    --num_top_k_batches $NUM_TOP_K_BATCHES \
    --text_encoder $TEXT_ENCODER \
    --text_mode $TEXT_MODE \
    --progress $PROGRESS \
    --log_interval $LOG_INTERVAL \
    2>&1 | tee "${SAVE_DIR}/train_log.txt"
