#!/bin/bash

# ============================================================
# LoTS-Net fully-supervised training script
# ============================================================

export CUDA_VISIBLE_DEVICES=0,1
NUM_GPUS=2
MASTER_PORT=$(python3 -c "
import socket
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind(('', 0))
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    print(s.getsockname()[1])
")
echo "[INFO] Using master port: $MASTER_PORT"

SEED=42
NUM_WORKERS=1

# ---- Data ----
# DATA_ROOT="data/GPCC_Resized_512_640_to_256_256_overlap_0_0"          # Replace with your data path
DATA_ROOT="data/MDC_Resized_256_320_to_256_256_overlap_0_0"          # Replace with your data path
VAL_RATIO=0.1
TEST_RATIO=0.1

# ---- Dataset split mode ----
# ""                        -> random split (default), using VAL_RATIO/TEST_RATIO
# "splits/split_sup.csv"    -> CSV preset split (recommended), generated by dataview.ipynb
#                             CSV must contain 'case_id' and 'split' (train/val/test) columns
#                             When set, VAL_RATIO/TEST_RATIO are ignored
# SPLIT_CSV=""
SPLIT_CSV="data/MDC_Resized_256_320_to_256_256_overlap_0_0/split_sup.csv"

# ---- Training hyperparameters ----
BATCH_SIZE=2
EPOCHS=150
LR=0.0004
NUM_CLASSES=2

# ---- LR schedule ----
# warmup_ratio: fraction of total epochs for linear warmup (0.2 = first 20% of epochs)
# Remaining (1 - warmup_ratio) epochs use cosine annealing down to eta_min=1e-6
WARMUP_RATIO=0.2

# ---- Early stopping ----
# Monitor Val Dice(all): stop training after consecutive epochs without improvement
# 0  -> disabled (default, run all EPOCHS)
# 20 -> stop after 20 epochs without a new best Val Dice (recommended starting point)
EARLY_STOP_PATIENCE=0

# ---- Window-best model checkpoint ----
# Save an extra best-validation model within [BEST_WINDOW_START, BEST_WINDOW_END]
# Compare with the global best to assess late-training overfitting
BEST_WINDOW_START=50
BEST_WINDOW_END=100

# ---- Model hyperparameters ----
IN_CHANS=60
# IN_CHANS=40
TEXT_DIM=1024
C_SPE=144
C_ATTN=144
ROUTER_TOP_K=15
STEM_CH=128
QUEUE_LEN=300
QUEUE_DEVICE="cuda"         # "cpu" or "cuda" (cuda reduces CPU->GPU transfer latency)

# ---- Queue retrieval mode ----
# "top1"    : paper Eq.1, global pool + argmax, very low VRAM (recommended)
# "chunked" : online-softmax chunked dense attention, numerically equivalent, bounded VRAM
RETRIEVAL_MODE="chunked"
QUEUE_CHUNK_SIZE=32         # chunked mode only: queue entries per chunk

# ---- Router temperature ----
# Top-K logits from scoring_mlp are divided by this temperature before softmax
# < 1.0 -> sharper weights (closer to hard selection, more focused gradients)
# > 1.0 -> softer weights (more uniform aggregation, better early exploration)
# 1.0   -> no scaling (default)
ROUTER_TEMPERATURE=1.0

# ---- SMD EMA bases ----
# "--smd_ema_bases"  -> enable (strongly recommended): persistent NMF bases + EMA update
#                     fixes wrong gradients from grad checkpoint + rand_init
#                     and stabilizes BatchNorm/GroupNorm running stats
# ""                -> disable: random NMF init every forward (original behavior, not recommended)
SMD_EMA_BASES="--smd_ema_bases"

# ---- DDP options ----
# "--find_unused_parameters" -> enable (for ablation runs with unused parameters)
# ""                         -> disable (lower comm overhead when all params are used)
FIND_UNUSED_PARAMS=""

# ---- Dice loss class weights ----
# ""                                  -> omit flag, equal bg/fg weights (default)
# "--dice_class_weights 0.0 1.0"      -> foreground-only Dice (ignore background)
# "--dice_class_weights 0.3 1.0"      -> foreground weight ~3.3x background
# "--dice_class_weights 0.5 1.0"      -> foreground weight 2x background (recommended start)
DICE_CLASS_WEIGHTS="--dice_class_weights 0.5 1.0"

# ---- CE loss class weights ----
# compute_metrics convention: index 0 = foreground weight, index 1 = background weight
# When bg:fg ~ 1.8:1, use [1.0, 1.8] -> bg dice weight 0.643, fg 0.357
# Val Dice(all) ~ 0.643*bg_dice + 0.357*fg_dice, more optimistic than equal weighting
# ""                                      -> omit flag, equal average (default)
# "--ce_class_weights 1.0 1.8"            -> fg weight 1.0, bg weight 1.8 (recommended)
CE_CLASS_WEIGHTS=""

# ---- CE/Dice global coefficients ----
# loss = ce_weight*CE + dice_weight*Dice
CE_WEIGHT=1.0
DICE_WEIGHT=1.0

# ---- Auxiliary head loss weight ----
# loss_total = loss_main + LAMBDA_AUX_SUP * loss_aux
# 0.0 disables auxiliary head loss (ablation)
LAMBDA_AUX_SUP=0.4

# ---- Logging ----
PROGRESS="log"              # tqdm / log / none
LOG_INTERVAL=20
TIMESTAMP=$(date "+%Y%m%d_%H%M%S")
EXP_NAME="Sup_LoTSNet_${TIMESTAMP}"
SAVE_DIR="./records/${EXP_NAME}"
mkdir -p "$SAVE_DIR"

echo "========================================================"
echo "Starting Fully-Supervised Training on $NUM_GPUS GPUs..."
echo "Experiment:      $EXP_NAME"
echo "Queue device:    $QUEUE_DEVICE"
echo "Retrieval mode:  $RETRIEVAL_MODE"
echo "Find unused:     ${FIND_UNUSED_PARAMS:-false}"
echo "Progress mode:   $PROGRESS"
echo "========================================================"

torchrun \
    --nproc_per_node=$NUM_GPUS \
    --master_port=$MASTER_PORT \
    train_sup.py \
    --seed $SEED \
    --num_workers $NUM_WORKERS \
    --save_dir "$SAVE_DIR" \
    --exp_name "$EXP_NAME" \
    --data_root "$DATA_ROOT" \
    --val_ratio $VAL_RATIO \
    --test_ratio $TEST_RATIO \
    ${SPLIT_CSV:+--split_csv "$SPLIT_CSV"} \
    --img_size 256 256 \
    --epochs $EPOCHS \
    --batch_size $BATCH_SIZE \
    --lr $LR \
    --warmup_ratio $WARMUP_RATIO \
    --early_stop_patience $EARLY_STOP_PATIENCE \
    --best_window_start $BEST_WINDOW_START \
    --best_window_end $BEST_WINDOW_END \
    --num_classes $NUM_CLASSES \
    --in_chans $IN_CHANS \
    --text_dim $TEXT_DIM \
    --c_spe $C_SPE \
    --c_attn $C_ATTN \
    --router_top_k $ROUTER_TOP_K \
    --stem_ch $STEM_CH \
    --queue_len $QUEUE_LEN \
    --queue_device $QUEUE_DEVICE \
    --retrieval_mode $RETRIEVAL_MODE \
    --queue_chunk_size $QUEUE_CHUNK_SIZE \
    --router_temperature $ROUTER_TEMPERATURE \
    $SMD_EMA_BASES \
    $FIND_UNUSED_PARAMS \
    $DICE_CLASS_WEIGHTS \
    $CE_CLASS_WEIGHTS \
    --ce_weight $CE_WEIGHT \
    --dice_weight $DICE_WEIGHT \
    --lambda_aux_sup $LAMBDA_AUX_SUP \
    --progress $PROGRESS \
    --log_interval $LOG_INTERVAL \
    2>&1 | tee "$SAVE_DIR/train_log.txt"
